name = "rss_filter_gleam"
version = "1.0.0"
target = "erlang"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "== 0.60.0"
wisp = "~> 2.0.0"
mist = "~> 5.0.0"
gleam_erlang = "~> 1.3.0"
xmlm = ">= 1.0.0 and < 2.0.0"
gleam_http = "~> 4.0.0"
birl = ">= 1.7.1 and < 2.0.0"
xmleam = ">= 1.1.5 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"


[dev-dependencies]
gleeunit = "~> 1.0"
